#spring:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true

spring:
  application:
    name: springboot-developer
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: hyen #id
    password: 1080 #pw

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

